### ISSUE TITLE
[typo] Fix hyperlink on text

### ISSUE THREAD

**Issue by jmbarrios** [gbif/course-introduction-to-gbif#22]
On section https://docs.gbif.org/course-introduction-to-gbif/es/principios-de-los-datos-mediados-por-gbif.html#identificadores-de-objeto-digital, there is a link to https://www.gbif.org/citation-guidelines but the render is faulty.

**Comment by jmbarrios** [comment]
On https://docs.gbif.org/course-introduction-to-gbif/es/principios-de-los-datos-mediados-por-gbif.html#datos-abiertos, there is another typo on a link

**Comment by jmbarrios** [comment]
Another typo on link on https://docs.gbif.org/course-introduction-to-gbif/es/m%C3%A9tricas-sobre-los-datos.html#m%C3%A9tricas-sobre-los-datos

**Comment by laurarussell** [comment]
Thanks for reporting these issues. I have fixed them (as well as others) in our CrowdIn translation service which integrates with GitHub. So please do not make manual commits via GitHub. I will soon be pushing my translation commits live.

**Comment by laurarussell** [comment]
#25 Fixes these reported issues, plus other broken links and images in the Spanish translation. May need to refresh the content to see fixes in production. Please continue to report issues if you find them. Thank you.
